(()=>{'use strict';
const api='https://mxflgcwrydqalcvfqhmd.supabase.co/functions/v1/calendar-api';
const btn=document.createElement('button');btn.className='tab';btn.textContent='📥 Importar Excel';btn.type='button';
document.querySelector('.tabs').append(btn);
const dlg=document.createElement('dialog');dlg.innerHTML='<form method="dialog" style="padding:20px;display:grid;gap:12px"><h3 style="margin:0">Importar estadísticas del partido</h3><label>Partido de Navia<select id="statGame" style="display:block;width:100%;padding:10px;margin-top:5px"></select></label><label>Archivo Excel (.xlsx)<input id="statExcel" type="file" accept=".xlsx,.xls" style="display:block;width:100%;margin-top:5px" required></label><label>Código privado de edición<input id="statCode" type="password" autocomplete="off" style="display:block;width:100%;padding:10px;margin-top:5px" required></label><div id="statMessage" style="font-size:13px;white-space:pre-wrap"></div><div style="display:flex;justify-content:flex-end;gap:8px"><button value="cancel" class="secondary">Cancelar</button><button id="statSave" type="button" class="primary">Comprobar Excel</button></div></form>';
document.body.append(dlg);
const by=id=>document.getElementById(id),message=by('statMessage'),save=by('statSave');
btn.onclick=()=>{const sel=by('statGame');sel.innerHTML='<option value="">Selecciona el partido</option>'+games.filter(g=>g.home==='NAV'||g.away==='NAV').map(g=>'<option value="'+g.id+'">J'+g.round+' · '+T[g.home]+' / '+T[g.away]+'</option>').join('');message.textContent='';dlg.showModal()};
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function parse(wb,g){const a=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});let team=null;const out=[];const n=x=>Number(x)||0;const pair=x=>{const m=String(x).match(/^(\d+)\s*\/\s*(\d+)$/);return m?[+m[1],+m[2]]:[0,0]};for(const r of a){const head=norm(r[0]);if(head.length>10){for(const code of [g.home,g.away]){if(head===norm(T[code])||(code==='SAN'&&head.includes('SANFER ADBA'))){team=code;break}}}const no=Number(r[0]),name=String(r[1]||'').trim();if(!team||!Number.isInteger(no)||no<0||no>99||!name||norm(name)==='TOTALES')continue;const two=pair(r[4]),three=pair(r[6]),ft=pair(r[8]);out.push({team_code:team,player_number:no,player_name:name,minutes:String(r[2]||''),points:n(r[3]),two_made:two[0],two_attempted:two[1],three_made:three[0],three_attempted:three[1],ft_made:ft[0],ft_attempted:ft[1],rebounds_def:n(r[10]),rebounds_off:n(r[11]),rebounds_total:n(r[12]),assists:n(r[13]),steals:n(r[14]),turnovers:n(r[15]),blocks_made:n(r[16]),blocks_received:n(r[17]),fouls_committed:n(r[18]),fouls_received:n(r[19]),efficiency:n(r[20]),plus_minus:n(r[21])})}return out}
save.onclick=async()=>{const g=games.find(x=>x.id===Number(by('statGame').value)),file=by('statExcel').files[0],code=by('statCode').value;if(!g||!file||!code){message.textContent='Selecciona partido, Excel y código.';return}save.disabled=true;try{if(!window.XLSX)throw Error('No se ha podido cargar el lector de Excel.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=parse(wb,g),h=rows.filter(x=>x.team_code===g.home),a=rows.filter(x=>x.team_code===g.away);if(!h.length||!a.length)throw Error('No se identificaron jugadores de los dos equipos. Comprueba el archivo.');const ph=h.reduce((s,r)=>s+r.points,0),pa=a.reduce((s,r)=>s+r.points,0);if(!confirm('Vista previa · Jornada '+g.round+'\n'+T[g.home]+': '+h.length+' jugadores, '+ph+' puntos\n'+T[g.away]+': '+a.length+' jugadores, '+pa+' puntos\n\nSe reemplazarán las estadísticas previas de este partido. ¿Continuar?'))return;message.textContent='Guardando en Supabase…';const res=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'import_stats',code,game_id:g.id,rows})}),j=await res.json();if(!res.ok)throw Error(j.error||'Error al guardar');message.textContent='✓ '+j.count+' jugadores guardados';by('statCode').value='';by('statExcel').value='';await loadStats();setTimeout(()=>dlg.close(),1000)}catch(e){message.textContent='⚠ '+e.message}finally{save.disabled=false}};
})();